[package]
name = "game-explorer"
version = "0.1.0"
authors = ["Manuel Krebs"]
edition = "2018"

[dependencies]
actix-rt = "1.0"
actix-web = "2.0"
actix-cors = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
